// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlaVet.Infrastructure.Data;

#nullable disable

namespace OlaVet.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OlaVetDbContext))]
    [Migration("20260205180956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OlaVet.Domain.Entities.EducationQualification", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<string>("Institute")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.Property<int?>("YearOfDegree")
                        .HasColumnType("int");

                    b.HasKey("EducationId");

                    b.HasIndex("VetId")
                        .HasDatabaseName("IX_EducationQualification_VetId");

                    b.ToTable("EducationQualification", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime?>("LastRestocked")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("IX_Inventory_MedicineId");

                    b.HasIndex("Quantity")
                        .HasDatabaseName("IX_Inventory_Quantity");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_Inventory_StoreId");

                    b.HasIndex("StoreId", "MedicineId")
                        .IsUnique()
                        .HasDatabaseName("IX_Inventory_Store_Medicine_Unique");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabId"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LabAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("LabId");

                    b.HasIndex("ContactNumber")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("IsActive", "Specialization")
                        .HasDatabaseName("IX_Lab_IsActive_Specialization");

                    b.ToTable("Lab", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabAppointment", b =>
                {
                    b.Property<int>("LabAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabAppointmentId"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("int");

                    b.HasKey("LabAppointmentId");

                    b.HasIndex("AppointmentDateTime")
                        .HasDatabaseName("IX_LabAppointment_AppointmentDateTime");

                    b.HasIndex("PetId");

                    b.HasIndex("StatusTypeId")
                        .HasDatabaseName("IX_LabAppointment_StatusTypeId");

                    b.HasIndex("PetOwnerId", "AppointmentDateTime")
                        .HasDatabaseName("IX_LabAppointment_Owner_DateTime");

                    b.HasIndex("LabId", "StatusTypeId", "AppointmentDateTime")
                        .HasDatabaseName("IX_LabAppointment_Lab_Status_Date_Covering");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LabId", "StatusTypeId", "AppointmentDateTime"), new[] { "PetId", "Notes" });

                    b.ToTable("LabAppointment", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabAppointmentTest", b =>
                {
                    b.Property<int>("LabAppointmentTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabAppointmentTestId"));

                    b.Property<int>("LabAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResultDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TestResult")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("LabAppointmentTestId");

                    b.HasIndex("LabAppointmentId")
                        .HasDatabaseName("IX_LabAppointmentTest_AppointmentId");

                    b.HasIndex("LabTestId");

                    b.ToTable("LabAppointmentTest", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabPayment", b =>
                {
                    b.Property<int>("LabPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabPaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LabAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LabPaymentId");

                    b.HasIndex("LabAppointmentId")
                        .IsUnique();

                    b.HasIndex("LabId");

                    b.HasIndex("PaymentDateTime")
                        .HasDatabaseName("IX_LabPayment_PaymentDateTime");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_LabPayment_TransactionId")
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("LabPayment", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabReview", b =>
                {
                    b.Property<int>("LabReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabReviewId"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LabAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LabReviewId");

                    b.HasIndex("LabAppointmentId")
                        .IsUnique();

                    b.HasIndex("LabId")
                        .HasDatabaseName("IX_LabReview_StoreId");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_LabReview_Rating");

                    b.HasIndex("ReviewDateTime")
                        .HasDatabaseName("IX_LabReview_ReviewDateTime");

                    b.ToTable("LabReview", null, t =>
                        {
                            t.HasCheckConstraint("CK_LabReview_Rating", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabTest", b =>
                {
                    b.Property<int>("LabTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabTestId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LabTestDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LabTestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LabTestType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TestFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TurnaroundTimeHours")
                        .HasColumnType("int");

                    b.HasKey("LabTestId");

                    b.HasIndex("LabTestName")
                        .HasDatabaseName("IX_LabTest_Name");

                    b.HasIndex("LabTestType")
                        .HasDatabaseName("IX_LabTest_Type");

                    b.ToTable("LabTest", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.MedicineType", b =>
                {
                    b.Property<int>("MedicineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineTypeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MedicineTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("IX_MedicineType_TypeName");

                    b.ToTable("MedicineType", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.RecordType", b =>
                {
                    b.Property<int>("RecordTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordTypeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecordTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("IX_RecordType_TypeName");

                    b.ToTable("RecordType", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.StatusType", b =>
                {
                    b.Property<int>("StatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusTypeId"));

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusTypeId");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("IX_StatusType_StatusName");

                    b.HasIndex("StatusName", "AppliesTo")
                        .IsUnique()
                        .HasDatabaseName("UQ_StatusType_Name_AppliesTo");

                    b.ToTable("StatusType", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.VetAppointmentType", b =>
                {
                    b.Property<int>("VetAppointmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VetAppointmentTypeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VetAppointmentTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("IX_VetAppointmentType_TypeName");

                    b.ToTable("VetAppointmentType", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RecordTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("VetId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("RecordTypeId")
                        .HasDatabaseName("IX_MedicalRecord_RecordTypeId");

                    b.HasIndex("VetId");

                    b.HasIndex("PetId", "RecordDate")
                        .HasDatabaseName("IX_MedicalRecord_Pet_Date");

                    b.HasIndex("PetId", "RecordTypeId")
                        .HasDatabaseName("IX_MedicalRecord_Timeline_Covering");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PetId", "RecordTypeId"), new[] { "RecordDate", "Diagnosis" });

                    b.ToTable("MedicalRecord", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MG")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MedicineTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("bit");

                    b.HasKey("MedicineId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Medicine_IsActive");

                    b.HasIndex("MedicineName")
                        .HasDatabaseName("IX_Medicine_MedicineName");

                    b.HasIndex("MedicineTypeId")
                        .HasDatabaseName("IX_Medicine_MedicineTypeId");

                    b.HasIndex("IsActive", "MedicineTypeId")
                        .HasDatabaseName("IX_Medicine_IsActive_MedicineTypeId");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.MedicineOrder", b =>
                {
                    b.Property<int>("MedicineOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineOrderId"));

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("OrderDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MedicineOrderId");

                    b.HasIndex("OrderDateTime")
                        .HasDatabaseName("IX_MedicineOrder_OrderDateTime");

                    b.HasIndex("PetOwnerId")
                        .HasDatabaseName("IX_MedicineOrder_PetOwnerId");

                    b.HasIndex("StatusTypeId")
                        .HasDatabaseName("IX_MedicineOrder_StatusTypeId");

                    b.HasIndex("StoreId", "StatusTypeId", "OrderDateTime")
                        .HasDatabaseName("IX_MedicineOrder_Store_Status_DateTime");

                    b.ToTable("MedicineOrder", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.MedicineOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Quantity] * [UnitPrice]", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("IX_MedicineOrderDetail_MedicineId");

                    b.HasIndex("MedicineOrderId")
                        .HasDatabaseName("IX_MedicineOrderDetail_MedicineOrderId");

                    b.ToTable("MedicineOrderDetails", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PetWeight")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PetId");

                    b.HasIndex("PetOwnerId")
                        .HasDatabaseName("IX_Pet_PetOwnerId");

                    b.HasIndex("RegistrationDate")
                        .HasDatabaseName("IX_Pet_RegistrationDate");

                    b.HasIndex("Species")
                        .HasDatabaseName("IX_Pet_Species");

                    b.HasIndex("PetOwnerId", "IsActive")
                        .HasDatabaseName("IX_Pet_PetOwnerId_IsActive");

                    b.ToTable("Pet", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.PetOwner", b =>
                {
                    b.Property<int>("PetOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetOwnerId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HomeAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Wallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("PetOwnerId");

                    b.HasIndex("ContactNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PetOwner_ContactNumber");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_PetOwner_Email");

                    b.HasIndex("RegistrationDate")
                        .HasDatabaseName("IX_PetOwner_RegistrationDate");

                    b.HasIndex("IsActive", "RegistrationDate")
                        .HasDatabaseName("IX_PetOwner_IsActive_RegistrationDate");

                    b.ToTable("PetOwner", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("ServiceDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("VetId", "ServiceType")
                        .HasDatabaseName("IX_Service_Vet_Type");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("Since")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoreAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StoreId");

                    b.HasIndex("ContactNumber")
                        .IsUnique();

                    b.HasIndex("StoreName")
                        .HasDatabaseName("IX_Store_Name");

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.StorePayment", b =>
                {
                    b.Property<int>("StorePaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StorePaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MedicineOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StorePaymentId");

                    b.HasIndex("MedicineOrderId")
                        .IsUnique();

                    b.HasIndex("PaymentDateTime")
                        .HasDatabaseName("IX_StorePayment_PaymentDateTime");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_StorePayment_TransactionId")
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("StorePayment", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.StoreReview", b =>
                {
                    b.Property<int>("StoreReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreReviewId"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MedicineOrderId")
                        .HasColumnType("int");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("StoreReviewId");

                    b.HasIndex("MedicineOrderId")
                        .IsUnique();

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_StoreReview_Rating");

                    b.HasIndex("ReviewDateTime")
                        .HasDatabaseName("IX_StoreReview_ReviewDateTime");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_StoreReview_StoreId");

                    b.ToTable("StoreReview", null, t =>
                        {
                            t.HasCheckConstraint("CK_StoreReview_Rating", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Vet", b =>
                {
                    b.Property<int>("VetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VetId"));

                    b.Property<string>("ClinicLocation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("VetId");

                    b.HasIndex("ContactNumber")
                        .IsUnique();

                    b.HasIndex("Specialization")
                        .HasDatabaseName("IX_Vet_Specialization");

                    b.HasIndex("YearsOfExperience")
                        .HasDatabaseName("IX_Vet_YearsOfExperience");

                    b.HasIndex("IsActive", "Specialization")
                        .HasDatabaseName("IX_Vet_IsActive_Specialization");

                    b.ToTable("Vet", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetAppointment", b =>
                {
                    b.Property<int>("VetAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VetAppointmentId"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("int");

                    b.Property<int>("VetAppointmentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("VetAppointmentId");

                    b.HasIndex("AppointmentDateTime")
                        .HasDatabaseName("IX_VetAppointment_AppointmentDateTime");

                    b.HasIndex("PetId");

                    b.HasIndex("PetOwnerId")
                        .HasDatabaseName("IX_VetAppointment_PetOwnerId");

                    b.HasIndex("StatusTypeId")
                        .HasDatabaseName("IX_VetAppointment_StatusTypeId");

                    b.HasIndex("VetAppointmentTypeId");

                    b.HasIndex("VetId")
                        .HasDatabaseName("IX_VetAppointment_VetId");

                    b.HasIndex("StatusTypeId", "AppointmentDateTime")
                        .HasDatabaseName("IX_VetAppointment_Status_DateTime_Covering");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StatusTypeId", "AppointmentDateTime"), new[] { "VetId", "PetId", "Reason" });

                    b.HasIndex("VetId", "AppointmentDateTime", "StatusTypeId")
                        .HasDatabaseName("IX_VetAppointment_Vet_DateTime_Status");

                    b.ToTable("VetAppointment", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("VetId", "DayOfWeek")
                        .HasDatabaseName("IX_VetAvailability_Vet_Day");

                    b.ToTable("VetAvailability", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetPayment", b =>
                {
                    b.Property<int>("VetPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VetPaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VetAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("VetPaymentId");

                    b.HasIndex("PaymentDateTime")
                        .HasDatabaseName("IX_VetPayment_PaymentDateTime");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_VetPayment_TransactionId")
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex("VetAppointmentId")
                        .IsUnique();

                    b.HasIndex("VetId");

                    b.ToTable("VetPayment", (string)null);
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetReview", b =>
                {
                    b.Property<int>("VetReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VetReviewId"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VetAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("VetReviewId");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_VetReview_Rating");

                    b.HasIndex("ReviewDateTime")
                        .HasDatabaseName("IX_VetReview_ReviewDateTime");

                    b.HasIndex("VetAppointmentId")
                        .IsUnique();

                    b.HasIndex("VetId")
                        .HasDatabaseName("IX_VetReview_VetId");

                    b.ToTable("VetReview", null, t =>
                        {
                            t.HasCheckConstraint("CK_VetReview_Rating", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.EducationQualification", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Vet", "Vet")
                        .WithMany("EducationQualifications")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Medicine", "Medicine")
                        .WithMany("Inventories")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabAppointment", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Lab", "Lab")
                        .WithMany("LabAppointments")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Pet", "Pet")
                        .WithMany("LabAppointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("LabAppointments")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Lookups.StatusType", "StatusType")
                        .WithMany("LabAppointments")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Pet");

                    b.Navigation("PetOwner");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabAppointmentTest", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.LabAppointment", "LabAppointment")
                        .WithMany("LabAppointmentTests")
                        .HasForeignKey("LabAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.LabTest", "LabTest")
                        .WithMany("LabAppointmentTests")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabAppointment");

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabPayment", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.LabAppointment", "LabAppointment")
                        .WithOne("LabPayment")
                        .HasForeignKey("OlaVet.Domain.Entities.LabPayment", "LabAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Lab", "Lab")
                        .WithMany("LabPayments")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("LabPayments")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("LabAppointment");

                    b.Navigation("PetOwner");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabReview", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.LabAppointment", "LabAppointment")
                        .WithOne("LabReview")
                        .HasForeignKey("OlaVet.Domain.Entities.LabReview", "LabAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Lab", "Lab")
                        .WithMany("LabReviews")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("LabReviews")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("LabAppointment");

                    b.Navigation("PetOwner");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Pet", "Pet")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Lookups.RecordType", "RecordType")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Vet", "Vet")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pet");

                    b.Navigation("PetOwner");

                    b.Navigation("RecordType");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Lookups.MedicineType", "MedicineType")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MedicineType");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.MedicineOrder", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("MedicineOrders")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Lookups.StatusType", "StatusType")
                        .WithMany("MedicineOrders")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Store", "Store")
                        .WithMany("MedicineOrders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PetOwner");

                    b.Navigation("StatusType");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.MedicineOrderDetail", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Medicine", "Medicine")
                        .WithMany("MedicineOrderDetails")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.MedicineOrder", "MedicineOrder")
                        .WithMany("MedicineOrderDetails")
                        .HasForeignKey("MedicineOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("MedicineOrder");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Pet", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("Pets")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetOwner");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Service", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Vet", "Vet")
                        .WithMany("Services")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.StorePayment", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.MedicineOrder", "MedicineOrder")
                        .WithOne("StorePayment")
                        .HasForeignKey("OlaVet.Domain.Entities.StorePayment", "MedicineOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("StorePayments")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Store", "Store")
                        .WithMany("StorePayments")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicineOrder");

                    b.Navigation("PetOwner");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.StoreReview", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.MedicineOrder", "MedicineOrder")
                        .WithOne("StoreReview")
                        .HasForeignKey("OlaVet.Domain.Entities.StoreReview", "MedicineOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("StoreReviews")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Store", "Store")
                        .WithMany("StoreReviews")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicineOrder");

                    b.Navigation("PetOwner");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetAppointment", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Pet", "Pet")
                        .WithMany("VetAppointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("VetAppointments")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Lookups.StatusType", "StatusType")
                        .WithMany("VetAppointments")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Lookups.VetAppointmentType", "VetAppointmentType")
                        .WithMany("VetAppointments")
                        .HasForeignKey("VetAppointmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Vet", "Vet")
                        .WithMany("VetAppointments")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("PetOwner");

                    b.Navigation("StatusType");

                    b.Navigation("Vet");

                    b.Navigation("VetAppointmentType");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetAvailability", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.Vet", "Vet")
                        .WithMany("Availabilities")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetPayment", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("VetPayments")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.VetAppointment", "VetAppointment")
                        .WithOne("VetPayment")
                        .HasForeignKey("OlaVet.Domain.Entities.VetPayment", "VetAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Vet", "Vet")
                        .WithMany("VetPayments")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetOwner");

                    b.Navigation("Vet");

                    b.Navigation("VetAppointment");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetReview", b =>
                {
                    b.HasOne("OlaVet.Domain.Entities.PetOwner", "PetOwner")
                        .WithMany("VetReviews")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.VetAppointment", "VetAppointment")
                        .WithOne("VetReview")
                        .HasForeignKey("OlaVet.Domain.Entities.VetReview", "VetAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlaVet.Domain.Entities.Vet", "Vet")
                        .WithMany("VetReviews")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetOwner");

                    b.Navigation("Vet");

                    b.Navigation("VetAppointment");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lab", b =>
                {
                    b.Navigation("LabAppointments");

                    b.Navigation("LabPayments");

                    b.Navigation("LabReviews");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabAppointment", b =>
                {
                    b.Navigation("LabAppointmentTests");

                    b.Navigation("LabPayment");

                    b.Navigation("LabReview");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.LabTest", b =>
                {
                    b.Navigation("LabAppointmentTests");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.MedicineType", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.RecordType", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.StatusType", b =>
                {
                    b.Navigation("LabAppointments");

                    b.Navigation("MedicineOrders");

                    b.Navigation("VetAppointments");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Lookups.VetAppointmentType", b =>
                {
                    b.Navigation("VetAppointments");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Medicine", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("MedicineOrderDetails");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.MedicineOrder", b =>
                {
                    b.Navigation("MedicineOrderDetails");

                    b.Navigation("StorePayment");

                    b.Navigation("StoreReview");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Pet", b =>
                {
                    b.Navigation("LabAppointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("VetAppointments");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.PetOwner", b =>
                {
                    b.Navigation("LabAppointments");

                    b.Navigation("LabPayments");

                    b.Navigation("LabReviews");

                    b.Navigation("MedicalRecords");

                    b.Navigation("MedicineOrders");

                    b.Navigation("Pets");

                    b.Navigation("StorePayments");

                    b.Navigation("StoreReviews");

                    b.Navigation("VetAppointments");

                    b.Navigation("VetPayments");

                    b.Navigation("VetReviews");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Store", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("MedicineOrders");

                    b.Navigation("StorePayments");

                    b.Navigation("StoreReviews");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.Vet", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("EducationQualifications");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Services");

                    b.Navigation("VetAppointments");

                    b.Navigation("VetPayments");

                    b.Navigation("VetReviews");
                });

            modelBuilder.Entity("OlaVet.Domain.Entities.VetAppointment", b =>
                {
                    b.Navigation("VetPayment");

                    b.Navigation("VetReview");
                });
#pragma warning restore 612, 618
        }
    }
}
